[package]
name = "."
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "00220680481960c1de446cd3e70951bcbf54e5c8"}
bigop = {git = "https://github.com/PatrickMassot/bigop", rev = "95354e18208b2847ad07539c2a0dfff78336f9b3"}
qelim = {git = "https://github.com/skbaek/qelim", rev = "99e9ca205a1fc061343dfac02fde0e973205d05d"}
