[package]
name = "."
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "fc6f57af2fceb52a97dba773425d0d33ebd5ec22"}
bigop = {git = "https://github.com/PatrickMassot/bigop", rev = "1a805a9b970f0696248c9e0a789e7fd2d8fb036a"}
